PreCommit:
  EsLint:
    enabled: true
    required_executable: './client/node_modules/.bin/eslint'
    include:
      - '**/*.js'
      - '**/*.jsx'

  HardTabs:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    exclude: '.git-hooks/**/*.rb'

  StyleLint:
    enabled: true
    description: 'Checking css files with stylelint'
    command: './client/node_modules/.bin/stylelint'
    flags: ['--formatter=json']
    include: '**/*.css'

  TrailingWhitespace:
    enabled: true
