PreCommit:
  HardTabs:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    exclude: '.git-hooks/**/*.rb'

  TrailingWhitespace:
    enabled: true
