PreCommit:
  EsLint:
    enabled: true
    required_executable: './client/node_modules/.bin/eslint'
    include:
      - '**/*.js'
      - '**/*.jsx'

  HardTabs:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
