require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - db/seeds.rb
    - Gemfile
    - Rakefile
    - config/initializers/*.rb

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/LineLength:
  Max: 100

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/infra/*

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
