require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
