language: ruby
bundler_args: "--without production"
cache: bundler
jobs:
  include:
  - stage: Lint
    script: bundle exec rubocop -c .rubocop.yml
  - stage: Test
    before_script: RAILS_ENV=test bundle exec rails db:create
    script: bundle exec rake spec
  - stage: Deploy
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_f01d31c5d2d1_key -iv $encrypted_f01d31c5d2d1_iv
      -in deploy_rsa.enc -out deploy_rsa -d
    - chmod 600 deploy_rsa
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: ssh -i deploy_rsa $DEPLOY_USER@$DEPLOY_HOST "sh ${DEPLOY_PATH}/bin/update"
env:
  global:
  - secure: 16NxzuG73q/aCw0yvfujVlpVcJ0F+ol3Zl3x5vHJ/ep1ii7k3Fv9cOBpUgoh/UgbqEM/IcvSGuHxIKvA1x+B7pCEgf0cYarS8l/kUqJ89rcW138EoLuSDaA+wcuvvharuH8pEMiXdyd+zxLhfXnUjGLeTzJ6ubgjxIMdSed2cyx1jCnGqWlc74fYyxulBfWLD4jrA5zqpxnZFw7ak3IOn5+g2Lz4Jy6SxryycoqA9I9cFQCQCFZ4T5vWx9z4yddOud4705Mg6OXI0kFH4j4PwZLIhp3dgL3+8INYr/DLas4FkgnlDyJVcTPhmnSTqpAI/JOJLSoOO/B8rifAQor4TXFS33Vzwn4qMIuOKp7QFJj/PkzgUdYDigt544LcVCPRDRfZOA/joL2+Wpd6RfYkv+AKapjR7Mn9kzmNTeWDwBiZnuryueZtp7kUwhYoZDNjN3uADxyOAIe1k/9I/9uipEl6VWx8xoV5INQwdRwLvXHj4VYWGTqalqG/meWAqhs4I6hxle+MFL/zdlCuQW1vdAMVht9/bcNmClZyOQFU9Ub3jL2EBPp/P8fD4UtU0GstYalaFFW/WKQLSWYxYVrkLB1/M7VPHZUjqW5KEkFNO8gHcXSaMgbWIp5/q3UURKNe5EBqP4Ym7pNcu6gTxSWJIWqW6GLTxJ6din+X6L001G8=
  - secure: mxe+PXbxWzmCyAfZXv0GOov994ddUTrVcjIfOZdgKQGayLzInDSJedzOk6PkTaSCY/+pMtYrr0/1tHL+6Nuw/LWXVtz3as4RbH+GEzP5Dj5ZsQ1YRwPWRqPn3YRMKABChOg6F1QT8cg8cUbiFr87rTOwDz9S8UkXQH96ECIdOtvy4KkM2jeNpU/Z3fY/92lXrqfwm6w7IZcaRhXng5K6ZXu8MoIskgmOUashfLEL9UAQTVAzg/tE97hp2ZezLmpe56MPJFEM7Kl97Dt2xNy61WDSkU9DeAr7PK64PDFuozKmXwUGW3JyQ2ObcEHUIqwBO4klAQHBwXtu6IMISsji2el5dFMzLfyICbPrcMXrkIOTR7JClWLPMoWO/G5+i33KMT9EaPXMDd9JuAAXHlstcIXhv6958CAM540odV0jzybYykwhUwLX9yRRqvk4YNzy+KaPnCFenuqWiUbR9FdDDqw2Wk0FG9Qx8QgHLfiLGf0mJX/kQ9tV9ThwMvbqJnvGSgOFafFTjxerkxcCSKm2cnb/SvrnXC3JKnMBxhpL9T+2JXG08VZz9Dvz60ufNFwpFYV2plCUakyBZSuZddLlZUVzltlGNhRwpEASedTC1NnV/wkkv3wDGZMqAnQlRNg6N/pLu6VlAlkMARC0Dj+UU3AvHxpdfGYvm5H4vZlpbGs=
  - secure: MuoRa34CLW6Fx/5US/z/jrY3imCenc6NZ9I6EVOHENnJw3QQDPwOfTgJ4/xhLVSsZr1o+AaR9A7lsmR1pURVFntADh1C9bYrtIycItYHy3MpNB8g0gsc5szI3/uk6fki8VY/x4eVVTGSvEURQE49Bf6FVpxY0IfDORLOwFSkeyToDALb2VfT7TEkeK8EU8Uhnf0ODXaaduL5Dsziid93HOvJJWOQ7Mx5jnbMi6rpLJ//v+xqU3XIS8XYUIY8rO0RIPzHALcxasjezE7o54GR57Vql9uqdqCP5Yeljm86qRvizgAD1IQCkZABQW7cvnJEPHGuNsfUtRfjS76rda+7HDgx+JmR7aSab3hfQ2TFbamnbL/62k50LR6NtgvCCQ/+crkbTncqzKzkxTz/O/Ivcc5iCp5OGOtkoesT0ukhyw+hfi94JHeqGvLr+crpmSy0/JqJWHWVIKtZEEhQqt+YW+eyCJ5rmchPg/2uIirOnCteFBJiXz6HqnrS4HoJsl2ux6RV+ukAS2HbbJQ3Ls/hdVDwArT/y4dunKkV4r/CDd+ArVlF2dEKoaCHzN7LCFdwP/OI7x150rGLNLgJkfOT9dVpNYW2DdsoOD10GzAFtAs60I8u/EHRUwXJxU0DmT3EBlnc6Gc6LpbiJdK/tN9S6sbzehd7CbQK72tMWck0Qz8=
addons:
  ssh_known_hosts:
    secure: ZZtCsdHc8uLgZkwoJPXZ0svl55EeC/Z40zmsrPLX3Lj7bJ0ng1GIhpLQvanitijHwLE4WShfrA47zTlNgfm0pCavpImuQxW2q8CfyFE3bjN3ZYWx2LvdIw6nA89ePVwG555YK62Z4BVKAa4gUpvs3X3KpfJSRqCY+jwMH3+8+XDlQa7wnUW/v3h3e/i02/uUS2KsG35QnUyySK4f4Oe4ntrKQbzlu0ZhM7FrODwZSnFOIpSWmaadbWiiWASu/UV5DLFOcn1O00XITHmINFYyXFxgkqQMLmpjnkf4/yeDvDbsdwy+9EQSrlJqaeawMTKJ5gD4eR4ef2A1ovoSXwWfeIt/aMeP5jYJIK7OkNoaChwaf5Cl913tbbQz/Xtduc9EKwTOHKkFo+l6BUh5bkX8F5WS05K3c54G0Op68DyEomVeq4ot67BD7HbWEr5tpPfHF1sZ6GQysOprv2PukAqMqmd0rnDSwZ69Oi9Fe0nx0ELnMbDEfB0mXx7ffy6mzgyqMOsxqUCHJXn5J9KEItTFK6Zj/EZVPks69spSgVuNRFUUlWQRGVIkGOu237UOPx15G0sfsvcfeOx6tZvNu0UlYe/vVOmYgwtkovfiSXnKTqclOeaXNsFmEnCE2Nr+cM9i4+mqw16jWARKrmo6W1wP5TEm1i6f2SnTQr8mQqU02Tw=
