language: ruby
bundler_args: --without production
cache: bundler
jobs:
  include:
    - stage: 'Lint'
      script: bundle exec rubocop -c .rubocop.yml
    - stage: 'Test'
      before_script: 'RAILS_ENV=test bundle exec rails db:create'
      script: bundle exec rake spec
