language: node_js
node_js:
  - 8
before_install: cd client
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls
