version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64

    environment:
      MYSQL_ROOT_PASSWORD: "test"

    ports:
      - 3306:3306

    volumes:
      - db:/var/lib/mysql

volumes:
  db:
