version: 2
jobs:
  build:

    working_directory: ~/app

    docker:
      - image: circleci/ruby:2.6.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

    steps:

      - checkout
      - restore_cache:
          keys: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install
      - save_cache:
          keys: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: ./go linter

workflows:
  version: 2
  pipeline:
    jobs:
      - build
