version: 2
jobs:
  build:

    working_directory: ~/app

    docker:
      - image: circleci/ruby:2.6.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: "test"

    steps:

      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: ./go linter

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: bin/rails db:create db:schema:load
      - run: ./go test-unit
      - run: ./go test-pact

workflows:
  version: 2
  pipeline:
    jobs:
      - build
