version: 2
jobs:
  build:

    working_directory: ~/app

    docker:
      - image: circleci/ruby:2.6.1

    steps:

      - checkout
      - run: bundle install
      - run: ./go linter

workflows:
  version: 2
  pipeline:
    jobs:
      - build
