default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: root
  password: test

development:
  <<: *default
  database: shelf2_development

test:
  <<: *default
  database: shelf2_test

production:
  <<: *default
  database: shelf2_production
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWORD'] %>
