default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: shelf2_development

test:
  <<: *default
  database: shelf2_test

<% if Rails.env.production? %>
production:
  <<: *default
  database: shelf2_production
  host: <%= Diplomat::Kv.get('shelf2-backend/db_host') %>
  password: <%= Diplomat::Kv.get('shelf2-backend/db_password') %>
<% end %>
