# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64275cfa11eaf7572f4badaeea570e661b32dd8fe8e0a4c6120f5b41c413f80f3eb10b56c51b5b5f3f0cdd363afa64749cbac9b7ac89c3aad56adef6f273cf29

test:
  secret_key_base: f792fd07c1c9b875cae6b44b0b81a68bc8f3106d3e4ed173b6021f026b231504fbc9721daf228b0495cbd711b2c0e25134cac376fdc24170e060d623a584f1c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
<% if Rails.env.production? %>
production:
  secret_key_base: <%= Diplomat::Kv.get('shelf2-backend/secret_key_base') %>
<% end %>
